### ISSUE TITLE
Not able create database schema

### ISSUE THREAD

**Issue by rudrahotta** [simplcommerce/SimplCommerce#291]
Hi,
Trying to play around, Have SQl Server 2012 express and using below connection string  and when I run the Update-Database from package manager console, I get below error.  Any thing I am doing wrong?

` "ConnectionStrings": {
    "DefaultConnection": "Server=DESKTOP-SCLTMOE\\SQLEXPRESS;Database=SimplCommerce;uid=sa;pwd=jsc2008.com;"
  },`

Error:
`System.Net.Sockets.SocketException (0x80004005): No such host is known
   at System.Net.Dns.InternalGetHostByName(String hostName, Boolean includeIPv6)
   at System.Net.Dns.GetHostAddresses(String hostNameOrAddress)
   at Npgsql.NpgsqlConnector.Connect(NpgsqlTimeout timeout)
   at Npgsql.NpgsqlConnector.<RawOpen>d__139.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlConnector.<Open>d__136.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlConnection.<Open>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.Internal.NpgsqlDatabaseCreator.Exists()
   at Microsoft.EntityFrameworkCore.Migrations.HistoryRepository.Exists()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
No such host is known`

**Comment by thiennn** [comment]
You are using PostgreSQL provider for Entity Framework but your connection string is for SQL Server

**Comment by hexpl0it** [comment]
How i can change provider? i would like to use sql server

**Comment by thiennn** [comment]
It's use SQL Server by default as you can see here https://github.com/simplcommerce/SimplCommerce/blob/841a62301e294de66279cdb94c1cc4da9bf30dae/src/SimplCommerce.WebHost/Program.cs#L32 and here https://github.com/simplcommerce/SimplCommerce/blob/841a62301e294de66279cdb94c1cc4da9bf30dae/src/SimplCommerce.WebHost/Extensions/ServiceCollectionExtensions.cs#L153

**Comment by thiennn** [comment]
@hexpl0it  Please describe steps you have done

**Comment by hexpl0it** [comment]
Oh, in my versione that files uses ngpsql. I download this repo and retry!

**Comment by rudrahotta** [comment]
thanks!
