### ISSUE TITLE
Database Migration failed

### ISSUE THREAD

**Issue by rafsanulhasan** [simplcommerce/SimplCommerce#550]
Update-Database command is not working. Show following error: 
System.InvalidOperationException: Unable to determine the relationship represented by navigation property 'User.UserAddresses' of type 'IList<UserAddress>'. Either manually configure the relationship, or ignore this property using the '[NotMapped]' attribute or by using 'EntityTypeBuilder.Ignore' in 'OnModelCreating'.
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.PropertyMappingValidationConvention.Apply(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelBuilt(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.OnModelBuilt(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.Model.Validate()
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.<>c__DisplayClass5_0.<GetModel>b__1()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.<>c.<TryAddCoreServices>b__7_1(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()
   at Microsoft.EntityFrameworkCore.Internal.InternalAccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.GetMigrations(String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.GetMigrationsImpl(String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.GetMigrations.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass4_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Unable to determine the relationship represented by navigation property 'User.UserAddresses' of type 'IList<UserAddress>'. Either manually configure the relationship, or ignore this property using the '[NotMapped]' attribute or by using 'EntityTypeBuilder.Ignore' in 'OnModelCreating'.

**Comment by thiennn** [comment]
you will need to copy the module.json of each module to the Host so that modules can be loaded correctly

**Comment by rafsanulhasan** [comment]
Oh ok, I missed the ste. 
Thanks!

**Comment by hishamco** [comment]
I have the same issue here, when I build the host application I got an error in:
```
<Target Name="CopyModules" AfterTargets="Build">
    <Exec WorkingDirectory="." Command="npm run gulp-copy-modules -- --configurationName $(ConfigurationName)" />
  </Target>
```

@thiennn how can I fix this coz I'm blocked

**Comment by thiennn** [comment]
@hishamco you will need to have nodejs installed in your PC. You can run this command directly in the command windows at the SimplCommerce.WebHost folder to see the problem in details

**Comment by hishamco** [comment]
I already did, I got the following exception
![exception](https://user-images.githubusercontent.com/3237266/45325505-b6e55600-b559-11e8-8494-ebf7e551b1ed.png)

**Comment by thiennn** [comment]
what is the node version on your PC? and please run npm install then run gulp copy ... again

**Comment by hishamco** [comment]
Node version is `v0.12.2`
I ran the above commands with no luck 😞

**Comment by thiennn** [comment]
Pleases install node 8.x or 10.x

**Comment by hishamco** [comment]
I installed version `8.11.4` and it works, I will try to run the migrations now
thanks

**Comment by hishamco** [comment]
I can confirm that everything is executing smoothly after updating the node, I think we need to close this

**Comment by rafsanulhasan** [comment]
After running gulp tasks (copy-lib,static,and mmodules), I ran Update Database in WebHost and got the following error.
`Unable to determine the relationship represented by navigation property 'User.UserAddresses' of type 'IList<UserAddress>'. Either manually configure the relationship, or ignore this property using the '[NotMapped]' attribute or by using 'EntityTypeBuilder.Ignore' in 'OnModelCreating'.`

**Comment by thiennn** [comment]
That error means that modules aren't load correctly. The module loader code can be found here https://github.com/simplcommerce/SimplCommerce/blob/93268fd79af4fe183497c50f565e4c08121e9a6b/src/SimplCommerce.WebHost/Extensions/ServiceCollectionExtensions.cs#L44

**Comment by hishamco** [comment]
@rafsanulhasan I ran into the same situation, just I removed gulp build from the .csproj task and run it manually in the CMD

**Comment by rafsanulhasan** [comment]
@hishamco would you please show me the steps
@thiennn I manually copied the required dll files into the bin folder of SimplCommerce.WebHost\Modules and then run gulp-tasks. It shows:
`System.InvalidOperationException: Unable to determine the relationship represented by navigation property 'Product.ProductLinks' of type 'IList<ProductLink>'. Either manually configure the relationship, or ignore this property using the '[NotMapped]' attribute or by using 'EntityTypeBuilder.Ignore' in 'OnModelCreating'.`
`Unable to determine the relationship represented by navigation property 'Product.ProductLinks' of type 'IList<ProductLink>'. Either manually configure the relationship, or ignore this property using the '[NotMapped]' attribute or by using 'EntityTypeBuilder.Ignore' in 'OnModelCreating'.`

**Comment by hishamco** [comment]
@rafsanulhasan first of all update the NodeJS, then run `npm run gulp-copy-modules -- --configurationName Debug"`

**Comment by rafsanulhasan** [comment]
@hishamco 
I have node version 9.3.0....
didn't work

**Comment by hishamco** [comment]
Could you let me know what happen when you execute the above command in npm?

**Comment by rafsanulhasan** [comment]
gulp worked when I changed [line 61](https://github.com/simplcommerce/SimplCommerce/blob/master/src/SimplCommerce.WebHost/gulpfile.js#line61) to `if (module.isBundledWithHost) {`

**update-database** failed with following:
`System.InvalidOperationException: Unable to determine the relationship represented by navigation property 'Product.ProductLinks' of type 'IList<ProductLink>'. Either manually configure the relationship, or ignore this property using the '[NotMapped]' attribute or by using 'EntityTypeBuilder.Ignore' in 'OnModelCreating'.`
`Unable to determine the relationship represented by navigation property 'Product.ProductLinks' of type 'IList<ProductLink>'. Either manually configure the relationship, or ignore this property using the '[NotMapped]' attribute or by using 'EntityTypeBuilder.Ignore' in 'OnModelCreating'.`

**Comment by hishamco** [comment]
Does all the module(s).json copied into the `Modules` folder? If yes be sure the `SimplCommerce.WebHost` project is selected when you run the `update-database` command

**Comment by rafsanulhasan** [comment]
Yes all modules are copied into `Modules` folder.
I have tried everything as you suggested but no luck.

**Comment by rafsanulhasan** [comment]
It might be a connection string issue. i fixed it to use a generic localdb which is installed with VS in PR #564 .
Thanks everyone.
