### ISSUE TITLE
NullReferenceException when clicking on a product from home page

### ISSUE THREAD

**Issue by MaherJendoubi** [simplcommerce/SimplCommerce#573]
Hi friends,

I am using Visual Studio 15.8.4.
dotnet --version : 2.2.100-preview2-009404

System.NullReferenceException: Object reference not set to an instance of an object.
   at SimplCommerce.Module.Localization.TagHelpers.LanguageDirectionTagHelperComponent.Process(TagHelperContext context, TagHelperOutput output) in C:\Users\Maher\Documents\GitHub\SimplCommerce\src\Modules\SimplCommerce.Module.Localization\TagHelpers\LanguageDirectionTagHelperComponent.cs:line 26
   at Microsoft.AspNetCore.Razor.TagHelpers.TagHelperComponent.ProcessAsync(TagHelperContext context, TagHelperOutput output)
   at Microsoft.AspNetCore.Mvc.Razor.TagHelpers.TagHelperComponentTagHelper.ProcessAsync(TagHelperContext context, TagHelperOutput output)
   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner.RunAsync(TagHelperExecutionContext executionContext)
   at AspNetCore.Views_Shared__Layout.ExecuteAsync()
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderLayoutAsync(ViewContext context, ViewBufferTextWriter bodyWriter)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ActionContext actionContext, IView view, ViewDataDictionary viewData, ITempDataDictionary tempData, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
   at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultAsync(IActionResult result)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResultFilterAsync[TFilter,TFilterAsync]()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultFilters()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by hishamco** [comment]
After a lot of investigation I come up with the following:
1-  This is not occur on the products page only, it occurs for all the requests after the first one
2- Strange part is `IRequestCultureFeature` isn't available in `LanguageDirectionTagHelperComponent` while it's available in views for instance `_SelectLanguagePatial`

this may occurs because:
- The localization setup has an issue
- Middlewares order
- Module architecture
- Or a bug

your thought @thiennn

**Comment by hishamco** [comment]
I can confirm now it's an MVC bug, so I will open an issue there

**Comment by MaherJendoubi** [comment]
It's strange, when you run Ctrl+F5 this bug disappears.

**Comment by hishamco** [comment]
> It's strange when you run Ctrl+F5 this bug disappears

Strange!! but still there's MVC localization issue bug

**Comment by thiennn** [comment]
If you change from Singleton to Transient for LanguageDirectionTagHelperComponent registration. The problem disappear

**Comment by hishamco** [comment]
AFAIK the `TagHelperComponent` should be registered as singleton, so let us keep this open for track the issue that I filed in the MVC repo

**Comment by MaherJendoubi** [comment]
Thank you @hishamco @thiennn for your answers.

**Comment by hishamco** [comment]
@MaherJendoubi I think we should make this open to track the MVC issue

**Comment by hishamco** [comment]
@MaherJendoubi feel free to close this while it's fixed, I don't think that registration type is made this strange behavior

**Comment by MaherJendoubi** [comment]
Thanks @hishamco
