### ISSUE TITLE
CMS Module issue when publishing to Azure App Service

### ISSUE THREAD

**Issue by ayoungarmarius** [simplcommerce/SimplCommerce#619]
Hello,

I just want to point out an issue I faced when trying to deploy SimplCommerce to an Azure App Service today.

After deploying, the URL was returning a generic error 'An error occurred while starting the application.'.  Upon digging into the logs via Kudo, I found this particular entry:

`Application startup exception: System.Exception: Cannot find main assembly for module SimplCommerce.Module.Cms
   at SimplCommerce.WebHost.Extensions.ServiceCollectionExtensions.AddModules(IServiceCollection services, String contentRootPath) in C:\Dev\SimplCommerce\src\SimplCommerce.WebHost\Extensions\ServiceCollectionExtensions.cs:line 64
   at SimplCommerce.WebHost.Startup.ConfigureServices(IServiceCollection services) in C:\Dev\SimplCommerce\src\SimplCommerce.WebHost\Startup.cs:line 35
--- End of stack trace from previous location where exception was thrown ---https://www.google.com/webhp?hl=en&sa=X&ved=0ahUKEwj4prL-ufzdAhWKnoMKHUfNA50QPAgH
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Initialize()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
crit: Microsoft.AspNetCore.Hosting.Internal.WebHost[6]
      Application startup exception
System.Exception: Cannot find main assembly for module SimplCommerce.Module.Cms
   at SimplCommerce.WebHost.Extensions.ServiceCollectionExtensions.AddModules(IServiceCollection services, String contentRootPath) in C:\Dev\SimplCommerce\src\SimplCommerce.WebHost\Extensions\ServiceCollectionExtensions.cs:line 64
   at SimplCommerce.WebHost.Startup.ConfigureServices(IServiceCollection services) in C:\Dev\SimplCommerce\src\SimplCommerce.WebHost\Startup.cs:line 35
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Initialize()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
Hosting environment: Production
Content root path: D:\home\site\wwwroot
Now listening on: http://127.0.0.1:24448
Application started. Press Ctrl+C to shut down.`

So, after screwing around with things for a while, I found a solution to the issue.  Copying the contents of 'SimplCommerce\src\Modules\SimplCommerce.Module.Cms\bin\Debug\netcoreapp2.1' to 'SimplCommerce\src\Modules\SimplCommerce.Module.Cms\bin\Release\netcoreapp2.1' causes the application to start deploying successfully!!

I had tried deploying to several different App Services with both the latest version of the code and the one last one committed in September, on the 30th.

I usually only work with simple .Net MVC projects, so I'm not very familiar with the structure of the application and I'm no expert by any means... I'm not sure if I missed a step or did something dumb, but I just wanted to post to let you know of this issue and possibly help anyone else facing the same problem.

Besides this issue though SimplCommerce seems like an awesome solution, thanks so much for your work!

**Comment by thiennn** [comment]
Thank you @ayoungarmarius , we have just made the Cms module part of the application so that it's easier for everyone to deploy. 
Btw, there are some docs you might want too look at. http://docs.simplcommerce.com/en/latest/
