### ISSUE TITLE
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.   

### ISSUE THREAD

**Issue by lisandroiraguen** [simplcommerce/SimplCommerce#626]
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at SimplCommerce.WebHost.Extensions.ServiceCollectionExtensions.RegisterModuleInitializerServices(ModuleInfo module, IServiceCollection& services)
   at SimplCommerce.WebHost.Extensions.ServiceCollectionExtensions.AddModules(IServiceCollection services, String contentRootPath)
   at SimplCommerce.WebHost.Startup.ConfigureServices(IServiceCollection services)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Initialize()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at SimplCommerce.WebHost.Program.Main(String[] args)

All works great in windows, but when I'm tring to deploy in a ubuntu linux server I got this error after configure and run postgresql ef
I feel like it's a kind of url bug when ist's tring to load *.dll modules

**Comment by thiennn** [comment]
@lisandroiraguen Do you have your codebase up to date with the latest master branch. Because I believe that I have throw a better error message for this https://github.com/simplcommerce/SimplCommerce/commit/bb1d517f91c99435f60cf6c4c8aa615e9d2d670c
