### ISSUE TITLE
running on ubuntu 18 error

### ISSUE THREAD

**Issue by acebesm** [simplcommerce/SimplCommerce#677]
after running sudo bash sudo bash simpl-build.sh, database was populated successfully.
then dotnet run makes error

ERROR: 
```codee@codee-pc:~/netcore/SimplCommerce/src/SimplCommerce.WebHost$ dotnet run
/usr/share/dotnet/sdk/2.1.403/Microsoft.Common.CurrentVersion.targets(2110,5): warning MSB3088: Could not read state file "obj/Debug/netcoreapp2.1/SimplCommerce.Module.Shipping.csprojAssemblyReference.cache". Access to the path '/home/codee/netcore/SimplCommerce/src/Modules/SimplCommerce.Module.Shipping/obj/Debug/netcoreapp2.1/SimplCommerce.Module.Shipping.csprojAssemblyReference.cache' is denied. [/home/codee/netcore/SimplCommerce/src/Modules/SimplCommerce.Module.Shipping/SimplCommerce.Module.Shipping.csproj]
/usr/share/dotnet/sdk/2.1.403/Microsoft.Common.CurrentVersion.targets(2110,5): warning MSB3088: Could not read state file "obj/Debug/netcoreapp2.1/SimplCommerce.Module.ProductRecentlyViewed.csprojAssemblyReference.cache". Access to the path '/home/codee/netcore/SimplCommerce/src/Modules/SimplCommerce.Module.ProductRecentlyViewed/obj/Debug/netcoreapp2.1/SimplCommerce.Module.ProductRecentlyViewed.csprojAssemblyReference.cache' is denied. 

[/home/codee/netcore/SimplCommerce/src/Modules/SimplCommerce.Module.ProductRecentlyViewed/SimplCommerce.Module.ProductRecentlyViewed.csproj]
/home/codee/netcore/SimplCommerce/src/SimplCommerce.WebHost/SimplCommerce.WebHost.csproj(71,5): error MSB4018: The "CopyModuleTask" task failed unexpectedly.
/home/codee/netcore/SimplCommerce/src/SimplCommerce.WebHost/SimplCommerce.WebHost.csproj(71,5): error MSB4018: System.IO.IOException: Directory not empty
/home/codee/netcore/SimplCommerce/src/SimplCommerce.WebHost/SimplCommerce.WebHost.csproj(71,5): error MSB4018:    at System.IO.FileSystem.RemoveDirectoryInternal(DirectoryInfo directory, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound)
/home/codee/netcore/SimplCommerce/src/SimplCommerce.WebHost/SimplCommerce.WebHost.csproj(71,5): error MSB4018:    at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
/home/codee/netcore/SimplCommerce/src/SimplCommerce.WebHost/SimplCommerce.WebHost.csproj(71,5): error MSB4018:    at SimplCommerce.MSBuildTasks.CopyModuleTask.CreateOrCleanDirectory(String path)
/home/codee/netcore/SimplCommerce/src/SimplCommerce.WebHost/SimplCommerce.WebHost.csproj(71,5): error MSB4018:    at SimplCommerce.MSBuildTasks.CopyModuleTask.Execute()
/home/codee/netcore/SimplCommerce/src/SimplCommerce.WebHost/SimplCommerce.WebHost.csproj(71,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
/home/codee/netcore/SimplCommerce/src/SimplCommerce.WebHost/SimplCommerce.WebHost.csproj(71,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask)

The build failed. Please fix the build errors and run again.
```

INFO: 
```codee@codee-pc:~/netcore/SimplCommerce/src/SimplCommerce.WebHost$ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.1.403
 Commit:    04e15494b6

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.403/

Host (useful for support):
  Version: 2.1.5
  Commit:  290303f510

.NET Core SDKs installed:
  2.1.403 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.5 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.5 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.5 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download```

**Comment by acebes** [comment]
ive change from:
    <TaskFolder Condition=" '$(MSBuildRuntimeType)' == 'Core' ">netcoreapp2.1</TaskFolder>
to:
    <TaskFolder Condition=" '$(MSBuildRuntimeType)' == 'Core' ">netcoreapp2.0</TaskFolder>

and also comment out:
            // app.UseHttpsRedirection();
because i dont know yet how to work with https in net core

STATUS NOW: 
swagger working (kudos everyone for adding this)
homepage working on http 
TY

**Comment by acebesm** [comment]
ive change from:
    <TaskFolder Condition=" '$(MSBuildRuntimeType)' == 'Core' ">netcoreapp2.1</TaskFolder>
to:
    <TaskFolder Condition=" '$(MSBuildRuntimeType)' == 'Core' ">netcoreapp2.0</TaskFolder>

and also comment out:
            // app.UseHttpsRedirection();
because i dont know yet how to work with https in net core

STATUS NOW: 
swagger working (kudos everyone for adding this)
homepage working on http 
TY
