### ISSUE TITLE
"CopyModuleTask" task failed unexpectedly

### ISSUE THREAD

**Issue by avjabalpur** [simplcommerce/SimplCommerce#873]
Hi, I have cloned the application, 1-2 time that worked perfectly, but now after some days, when I tried to Build/Run then getting the following error

  Error	MSB4018	The "CopyModuleTask" task failed unexpectedly.
System.IO.IOException: The directory is not empty.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound, WIN32_FIND_DATA& data)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at System.IO.DirectoryInfo.Delete(Boolean recursive)
   at SimplCommerce.MSBuildTasks.CopyModuleTask.CreateOrCleanDirectory(String path)
   at SimplCommerce.MSBuildTasks.CopyModuleTask.CopyModule(Module module)
   at SimplCommerce.MSBuildTasks.CopyModuleTask.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()

**Comment by thiennn** [comment]
Please get the latest code
