### ISSUE TITLE
I can't launch the site on a docker container using a local built-in image

### ISSUE THREAD

**Issue by MaherJendoubi** [simplcommerce/SimplCommerce#96]
λ docker logs c0
Project SimplCommerce.Infrastructure (.NETStandard,Version=v1.6) will be compiled because inputs were modified
Compiling SimplCommerce.Infrastructure for .NETStandard,Version=v1.6
Compilation succeeded.
    0 Warning(s)
    0 Error(s)
Time elapsed 00:00:01.4304751
Project SimplCommerce.Module.Core (.NETStandard,Version=v1.6) will be compiled because dependencies changed
Compiling SimplCommerce.Module.Core for .NETStandard,Version=v1.6
Compilation succeeded.
    0 Warning(s)
    0 Error(s)
Time elapsed 00:00:01.7485746
Project SimplCommerce.Module.Localization (.NETStandard,Version=v1.6) will be compiled because dependencies changed
Compiling SimplCommerce.Module.Localization for .NETStandard,Version=v1.6
Compilation succeeded.
    0 Warning(s)
    0 Error(s)
Time elapsed 00:00:01.2585620
Project SimplCommerce.WebHost (.NETCoreApp,Version=v1.1) will be compiled because dependencies changed
Compiling SimplCommerce.WebHost for .NETCoreApp,Version=v1.1
Compilation succeeded.
    0 Warning(s)
    0 Error(s)
Time elapsed 00:00:01.8700001

System.AggregateException: One or more errors occurred. (No such device or address) ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException: No such device or address
   at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
   at System.Net.Dns.EndGetHostAddresses(IAsyncResult asyncResult)
   at System.Net.Dns.<>c.<GetHostAddressesAsync>b__14_1(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Npgsql.NpgsqlConnector.Connect(NpgsqlTimeout timeout)
   at Npgsql.NpgsqlConnector.RawOpen(NpgsqlTimeout timeout)
   at Npgsql.NpgsqlConnector.Open(NpgsqlTimeout timeout)
   at Npgsql.NpgsqlConnection.OpenInternal()
   at Microsoft.EntityFrameworkCore.Storage.Internal.NpgsqlDatabaseCreator.Exists()
   at Microsoft.EntityFrameworkCore.Migrations.HistoryRepository.Exists()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
---> (Inner Exception #0) System.Net.Internals.SocketExceptionFactory+ExtendedSocketException: No such device or address
   at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
   at System.Net.Dns.EndGetHostAddresses(IAsyncResult asyncResult)
   at System.Net.Dns.<>c.<GetHostAddressesAsync>b__14_1(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)<---
One or more errors occurred. (No such device or address)
Project SimplCommerce.Infrastructure (.NETStandard,Version=v1.6) will be compiled because inputs were modified
Compiling SimplCommerce.Infrastructure for .NETStandard,Version=v1.6
Compilation succeeded.
    0 Warning(s)
    0 Error(s)
Time elapsed 00:00:01.3883993
Project SimplCommerce.Module.Core (.NETStandard,Version=v1.6) will be compiled because dependencies changed
Compiling SimplCommerce.Module.Core for .NETStandard,Version=v1.6
Compilation succeeded.
    0 Warning(s)
    0 Error(s)
Time elapsed 00:00:01.7723728
Project SimplCommerce.Module.Localization (.NETStandard,Version=v1.6) will be compiled because dependencies changed
Compiling SimplCommerce.Module.Localization for .NETStandard,Version=v1.6
Compilation succeeded.
    0 Warning(s)
    0 Error(s)
Time elapsed 00:00:01.2423402
Project SimplCommerce.WebHost (.NETCoreApp,Version=v1.1) will be compiled because dependencies changed
Compiling SimplCommerce.WebHost for .NETCoreApp,Version=v1.1
Compilation succeeded.
    0 Warning(s)
    0 Error(s)
Time elapsed 00:00:01.9795459

System.AggregateException: One or more errors occurred. (No such device or address) ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException: No such device or address
   at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
   at System.Net.Dns.EndGetHostAddresses(IAsyncResult asyncResult)
   at System.Net.Dns.<>c.<GetHostAddressesAsync>b__14_1(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Npgsql.NpgsqlConnector.Connect(NpgsqlTimeout timeout)
   at Npgsql.NpgsqlConnector.RawOpen(NpgsqlTimeout timeout)
   at Npgsql.NpgsqlConnector.Open(NpgsqlTimeout timeout)
   at Npgsql.NpgsqlConnection.OpenInternal()
   at Microsoft.EntityFrameworkCore.Storage.Internal.NpgsqlDatabaseCreator.Exists()
   at Microsoft.EntityFrameworkCore.Migrations.HistoryRepository.Exists()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
---> (Inner Exception #0) System.Net.Internals.SocketExceptionFactory+ExtendedSocketException: No such device or address
   at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
   at System.Net.Dns.EndGetHostAddresses(IAsyncResult asyncResult)
   at System.Net.Dns.<>c.<GetHostAddressesAsync>b__14_1(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)<---
One or more errors occurred. (No such device or address)
Project SimplCommerce.Infrastructure (.NETStandard,Version=v1.6) will be compiled because inputs were modified
Compiling SimplCommerce.Infrastructure for .NETStandard,Version=v1.6
Compilation succeeded.
    0 Warning(s)
    0 Error(s)
Time elapsed 00:00:01.5453122
Project SimplCommerce.Module.Core (.NETStandard,Version=v1.6) will be compiled because dependencies changed
Compiling SimplCommerce.Module.Core for .NETStandard,Version=v1.6
Compilation succeeded.
    0 Warning(s)
    0 Error(s)
Time elapsed 00:00:01.6485679
Project SimplCommerce.Module.Localization (.NETStandard,Version=v1.6) will be compiled because dependencies changed
Compiling SimplCommerce.Module.Localization for .NETStandard,Version=v1.6
Compilation succeeded.
    0 Warning(s)
    0 Error(s)
Time elapsed 00:00:01.2480302
Project SimplCommerce.WebHost (.NETCoreApp,Version=v1.1) will be compiled because dependencies changed
Compiling SimplCommerce.WebHost for .NETCoreApp,Version=v1.1
Compilation succeeded.
    0 Warning(s)
    0 Error(s)
Time elapsed 00:00:01.9196247

System.AggregateException: One or more errors occurred. (No such device or address) ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException: No such device or address
   at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
   at System.Net.Dns.EndGetHostAddresses(IAsyncResult asyncResult)
   at System.Net.Dns.<>c.<GetHostAddressesAsync>b__14_1(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Npgsql.NpgsqlConnector.Connect(NpgsqlTimeout timeout)
   at Npgsql.NpgsqlConnector.RawOpen(NpgsqlTimeout timeout)
   at Npgsql.NpgsqlConnector.Open(NpgsqlTimeout timeout)
   at Npgsql.NpgsqlConnection.OpenInternal()
   at Microsoft.EntityFrameworkCore.Storage.Internal.NpgsqlDatabaseCreator.Exists()
   at Microsoft.EntityFrameworkCore.Migrations.HistoryRepository.Exists()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
---> (Inner Exception #0) System.Net.Internals.SocketExceptionFactory+ExtendedSocketException: No such device or address
   at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
   at System.Net.Dns.EndGetHostAddresses(IAsyncResult asyncResult)
   at System.Net.Dns.<>c.<GetHostAddressesAsync>b__14_1(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)<---
One or more errors occurred. (No such device or address)

**Comment by MaherJendoubi** [comment]
Steps to reproduce the issue : 
* docker build -t test .
* docker run --name simpldbtest -d postgres
* docker run --name simplsitetest -d -p 6000:6000 --link simpldbtest:simpldbtest test

**Comment by MaherJendoubi** [comment]
When I open a browser on localhost:6000 my container exits : 
docker ps -a
CONTAINER ID        IMAGE                         COMMAND                  CREATED             STATUS                      PORTS                    NAMES
c0317531be7a        test                          "/docker-entrypoin..."   7 hours ago         Exited (1) 53 seconds ago                            simplsitetest
4c7a5145ef62        postgres                      "/docker-entrypoin..."   7 hours ago         Up 2 minutes                5432/tcp                 simpldbtest
8b659e56fc06        simplcommerce/nightly-build   "/docker-entrypoin..."   23 hours ago        Exited (255) 14 hours ago   0.0.0.0:5000->5000/tcp   simplsite
d2fbaa2b6b13        postgres                      "/docker-entrypoin..."   23 hours ago        Exited (255) 14 hours ago   5432/tcp                 simpldb

**Comment by thiennn** [comment]
The postgres container should be linked as 'simplcommerce'. Because the database connection string using that name https://github.com/simplcommerce/SimplCommerce/blob/master/src/SimplCommerce.WebHost/appsettings.docker.json

**Comment by MaherJendoubi** [comment]
@thiennn I can't see SimplCommerce on the port 6000.

**Comment by MaherJendoubi** [comment]
@thiennn I fixed it thanks a lot 👍 
I did  docker run --name simplsite3 -d -p 8000:5000 --link simpldbtest:simpldb test
